name: Deploy to Production

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # Si tu as mis tes secrets dans un Environment (ex: production), décommente la ligne ci-dessous
    # environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Écrit la clé privée depuis le secret dans un fichier (en préservant les retours à la ligne)
      - name: Prepare SSH key file
        id: keyfile
        shell: bash
        run: |
          set -euo pipefail
          KEY_PATH="$RUNNER_TEMP/gha_deploy_key"
          umask 177
          cat > "$KEY_PATH" <<'KEY' ${{ secrets.SSH_KEY }} KEY
          # Vérifie que la clé est valide
          ssh-keygen -lf "$KEY_PATH" || { echo "❌ SSH_KEY invalide"; exit 1; }
          echo "KEY_PATH=$KEY_PATH" >> "$GITHUB_ENV"

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key_path: ${{ env.KEY_PATH }}
          script_stop: true
          command_timeout: "20m"
          debug: true
          script: |
            set -euo pipefail

            echo "➡️  Aller dans le dossier"
            cd ${{ secrets.REMOTE_PATH }}

            echo "➡️  Récupération du code"
            if [ ! -d ".git" ]; then
              git init
              git remote add origin git@github.com:${{ github.repository }}.git
              git fetch origin main
              git checkout -t origin/main
            else
              git fetch origin main
              git checkout main
              git reset --hard origin/main
            fi

            echo "➡️  Dépendances (prod)"
            ${{ secrets.COMPOSER_BIN }} install --no-dev --prefer-dist --no-interaction --optimize-autoloader

            echo "➡️  Nettoyage caches"
            ${{ secrets.PHP_CMD }} artisan config:clear || true
            ${{ secrets.PHP_CMD }} artisan route:clear || true
            ${{ secrets.PHP_CMD }} artisan view:clear || true

            echo "➡️  Reconstruction caches"
            ${{ secrets.PHP_CMD }} artisan config:cache
            ${{ secrets.PHP_CMD }} artisan route:cache
            ${{ secrets.PHP_CMD }} artisan view:cache

            echo "➡️  Migrations"
            ${{ secrets.PHP_CMD }} artisan migrate --force

            echo "➡️  Liens & queues"
            ${{ secrets.PHP_CMD }} artisan storage:link || true
            ${{ secrets.PHP_CMD }} artisan queue:restart || true

            echo "➡️  Permissions"
            chgrp -R www-data storage bootstrap/cache || true
            chmod -R ug+rwx storage bootstrap/cache || true

            echo "✅ Déploiement terminé"
