- name: Deploy over SSH
  uses: appleboy/ssh-action@v1.0.3
  env:
    REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
    PHP_CMD: ${{ secrets.PHP_CMD }}
    COMPOSER_BIN: ${{ secrets.COMPOSER_BIN }}
    GIT_BRANCH: ${{ secrets.GIT_BRANCH || 'main' }}
    PHP_FPM_SERVICE: ${{ secrets.PHP_FPM_SERVICE || 'php8.3-fpm' }}
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    port: ${{ secrets.SSH_PORT }}
    key: ${{ secrets.SSH_KEY }}
    script_stop: true
    command_timeout: "20m"
    debug: true
    # ⚠️ Ici on envoie UNIQUEMENT LES NOMS
    envs: REMOTE_PATH,PHP_CMD,COMPOSER_BIN,GIT_BRANCH,PHP_FPM_SERVICE
    script: |
      set -euo pipefail
      umask 002

      : "${REMOTE_PATH:?REMOTE_PATH secret requis}"
      PHP_CMD="${PHP_CMD:-php}"
      COMPOSER_BIN="${COMPOSER_BIN:-composer}"
      GIT_BRANCH="${GIT_BRANCH:-main}"
      PHP_FPM_SERVICE="${PHP_FPM_SERVICE:-php8.3-fpm}"

      echo "➡️  Cibles:"
      echo "  - path:  ${REMOTE_PATH}"
      echo "  - php:   ${PHP_CMD}"
      echo "  - comp:  ${COMPOSER_BIN}"
      echo "  - branch:${GIT_BRANCH}"
      echo "  - fpm:   ${PHP_FPM_SERVICE}"

      cd -- "${REMOTE_PATH}"
      echo "➡️  whoami=$(whoami)  pwd=$(pwd)"

      git config --global --add safe.directory "${REMOTE_PATH}" || true

      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      if ! grep -q "github.com" ~/.ssh/known_hosts 2>/dev/null; then
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts 2>/dev/null || true
      fi
      chmod 600 ~/.ssh/known_hosts || true

      echo "➡️  Fetch/reset sur ${GIT_BRANCH}"
      set -x
      git fetch --prune origin
      git checkout -B "${GIT_BRANCH}" "origin/${GIT_BRANCH}"
      git reset --hard "origin/${GIT_BRANCH}"
      set +x

      echo "➡️  Maintenance ON"
      ${PHP_CMD} artisan down --render="errors::503" || true

      echo "➡️  Composer install (prod)"
      ${COMPOSER_BIN} install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      echo "➡️  Migrate --force"
      ${PHP_CMD} artisan migrate --force

      echo "➡️  Clear caches"
      ${PHP_CMD} artisan config:clear || true
      ${PHP_CMD} artisan route:clear  || true
      ${PHP_CMD} artisan view:clear   || true

      echo "➡️  Rebuild caches"
      ${PHP_CMD} artisan config:cache
      ${PHP_CMD} artisan route:cache
      ${PHP_CMD} artisan view:cache

      echo "➡️  Storage & queues"
      ${PHP_CMD} artisan storage:link    || true
      ${PHP_CMD} artisan queue:restart   || true
      ${PHP_CMD} artisan horizon:terminate || true  # si Horizon

      echo "➡️  Permissions"
      mkdir -p storage/framework/{cache,views,sessions}
      chgrp -R www-data storage bootstrap/cache || true
      chmod -R ug+rwx storage bootstrap/cache   || true

      echo "➡️  Maintenance OFF"
      ${PHP_CMD} artisan up

      echo "➡️  Reload PHP-FPM"
      sudo -n systemctl reload "${PHP_FPM_SERVICE}" || true

      echo "✅ Déploiement terminé"
